apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gatus.stormspirit.tech
  namespace: gatus
  labels:
    'use-http01-solver': 'true'
spec:
  commonName: gatus.stormspirit.tech
  secretName: gatus.stormspirit.tech.cert
  dnsNames:
    - gatus.stormspirit.tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gatus
  namespace: gatus
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gatus.stormspirit.tech`)
      services:
        - name: gatus
          port: 80
  tls:
    secretName: gatus.stormspirit.tech.cert
