apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: main
  namespace: grassroots
spec:
  retentionPeriod: "3"
  removePvcAfterDelete: false
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: main
  namespace: grassroots
spec:
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-main.grassroots.svc:8429/api/v1/write"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor-metrics
  namespace: grassroots
spec:
  scheme: "https"
  tlsConfig:
    insecureSkipVerify: true
    caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - targetLabel: __address__
      replacement: kubernetes.default.svc:443
    - sourceLabels: [__meta_kubernetes_node_name]
      regex: (.+)
      targetLabel: __metrics_path__
      replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
  metricRelabelConfigs:
    - action: replace
      source_labels: [pod]
      regex: "(.+)"
      target_label: pod_name
      replacement: "${1}"
    - action: replace
      source_labels: [container]
      regex: "(.+)"
      target_label: container_name
      replacement: "${1}"
    - action: replace
      target_label: name
      replacement: k8s_stub
    - action: replace
      source_labels: [id]
      regex: '^/system\.slice/(.+)\.service$'
      target_label: systemd_service_name
      replacement: "${1}"
