apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault.prod.grassecon.org
  namespace: grassroots
  labels:
    "use-http01-solver": "true"
spec:
  commonName: vault.prod.grassecon.org
  secretName: vault.prod.grassecon.org.cert
  dnsNames:
    - vault.prod.grassecon.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-server
  namespace: grassroots
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.prod.grassecon.org`)
      kind: Rule
      services:
        - name: vault-internal
          port: 8200
  tls:
    secretName: vault.prod.grassecon.org.cert
