apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault.sarafu.network
  namespace: grassroots
  labels:
    "use-http01-solver": "true"
spec:
  commonName: vault.sarafu.network
  secretName: vault.sarafu.network.cert
  dnsNames:
    - vault.sarafu.network
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-server
  namespace: grassroots
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.sarafu.network`)
      kind: Rule
      services:
        - name: vault-internal
          port: 8200
  tls:
    secretName: vault.sarafu.network.cert
