apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: main
  namespace: grassroots
spec:
  retentionPeriod: "3"
  removePvcAfterDelete: false
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
