apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitabu-node
  labels:
    app: kitabu-node
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
