apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kitabu-node
  labels:
    app: kitabu-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitabu-node
  serviceName: kitabu-node
  template:
    metadata:
      labels:
        app: kitabu-node
        name: kitabu-node
    spec:
      terminationGracePeriodSeconds: 20
      initContainers:
        - name: data-permission-fix
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/bin/chown -R 1000:1000 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: pv
              mountPath: /data
      containers:
        - image: openethereum/openethereum:v3.3.3
          name: openethereum
          imagePullPolicy: IfNotPresent
          args:
            [
              "--bootnodes=enode://14589fd50ee2af6a96cc212ff4e5721d3896719f0d22f964d859effc5edf14fa65822ae7656dfe9bd51845f2dcd95032274631452f8954797b3e1b60ef135884@206.189.27.27:30303,enode://66eae4845b0909bd26ab2652054794ed6b88cc39aeb6efc7aa4a282230f46dbb9fab177e53b2fee2d33893798665f5772d6c9c6b551bd732a74706d491160166@134.209.177.55:30303,enode://b5b5c80c93a96ff61762ed25072aabc02c8db4a19e973d59eefb6f1ad5dd1c5c1a485c97c3d96ec03135025ac717140d4375332cd5253c4ac1ccbe2f3ee571f6@142.93.38.53:30303,enode://3937ff4695eeca27b968f691dd6fe7ad644439b536121c9f84cb3765c4d1d113a584c431e1f05f8f778fb27e910671129a7325e912dd48f75292fcadf73e367f@217.197.91.175:30313",
              "--config=/config/config.toml",
              "--jsonrpc-port=8547",
              "--jsonrpc-cors=all",
              "--jsonrpc-interface=all",
              "--jsonrpc-hosts=all",
              "--jsonrpc-apis=web3,eth,net,parity",
              "--ws-port=8548",
              "--ws-interface=all",
              "--ws-hosts=all",
              "--ws-origins=all",
            ]
          ports:
            - containerPort: 8547
            - containerPort: 8548
            - containerPort: 30303
          volumeMounts:
            - name: kitabu-node-config
              mountPath: /config
              readOnly: true
            - name: pv
              mountPath: /data
      volumes:
        - name: kitabu-node-config
          configMap:
            name: kitabu-node-config
            items:
        - name: pv
          persistentVolumeClaim:
            claimName: kitabu-node
