apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kitabu-node
  labels:
    app: kitabu-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitabu-node
  serviceName: kitabu-node
  template:
    metadata:
      labels:
        app: kitabu-node
        name: kitabu-node
    spec:
      terminationGracePeriodSeconds: 20
      initContainers:
        - name: data-permission-fix
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["/bin/chown -R 1000:1000 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: pv
              mountPath: /data
      containers:
        - image: openethereum/openethereum:v3.3.3
          name: openethereum
          imagePullPolicy: IfNotPresent
          args:
            [
              "--bootnodes=enode://0f0741b4244cc88d3fa275a37c30da4455d2bfcc8472519772dafcbf039b156ff2defa661088a071c9128139329c4c510bcd42f706f6f9e0bf8a5735e3bc0ac0@165.22.126.72:30303,enode://81957cebe2dea51c245b8df4f18de4a19d709e7551ba3398e3da33291025c1cbf5edf9c0c585765b73c5ed6777b3274a5df803a04438e022b7a6016d333398f4@142.93.38.53:30303,enode://76ca34f5cd3ea363ba9a4110faa09c02e7e4c626279a71f45ac48fc7bb90a532aaeb383492f68b5ed968ece954b37cb787857f8d58436eda4e864047e0be34b2@143.244.142.41:30303",
              "--config=/config/config.toml",
              "--jsonrpc-port=8547",
              "--jsonrpc-cors=all",
              "--jsonrpc-interface=all",
              "--jsonrpc-hosts=all",
              "--jsonrpc-apis=web3,eth,net,parity",
              "--ws-port=8548",
              "--ws-interface=all",
              "--ws-hosts=all",
              "--ws-origins=all",
            ]
          ports:
            - containerPort: 8547
            - containerPort: 8548
            - containerPort: 30303
          volumeMounts:
            - name: kitabu-node-config
              mountPath: /config
              readOnly: true
            - name: pv
              mountPath: /data
      volumes:
        - name: kitabu-node-config
          configMap:
            name: kitabu-node-config
            items:
        - name: pv
          persistentVolumeClaim:
            claimName: kitabu-node
