apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-cache-server
  labels:
    app: cic-cache-server
spec:
  selector:
    matchLabels:
      app: cic-cache-server
  replicas: 1
  template:
    metadata:
      labels:
        app: cic-cache-server
        group: cic-stack
    spec:
      containers:
        - name: cic-cache-server
          image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/cic-cache:0.5.93
          imagePullPolicy: Always
          command:
            [
              "/usr/local/bin/uwsgi",
              "--wsgi-file=/root/cic_cache/runnable/daemons/server.py",
              "--http=:8000",
              "--pyargv",
              "-v",
            ]
          envFrom:
            - configMapRef:
                name: postgres-common
            - configMapRef:
                name: evm-common
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
            - name: SERVER_PORT
              value: "8000"
          ports:
            - containerPort: 8000
              name: server
      restartPolicy: Always
