apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: s3-backup
  namespace: grassroots
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: walg-env
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: apps/pg-wal-backup
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: apps/pg-wal-backup
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: apps/pg-wal-backup
        property: AWS_ENDPOINT
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zalando-override
  namespace: grassroots
data:
  ALLOW_NOSSL: "true"
  WALG_COMPRESSION_METHOD: "brotli"
  USE_WALG_RESTORE: "true"
  USE_WALG_BACKUP: "true"
  BACKUP_SCHEDULE: "*/15 * * * *"
  BACKUP_NUM_TO_RETAIN: "100"
  AWS_REGION: ""
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: acid-cic-prod
  namespace: grassroots
spec:
  allowedSourceRanges: null
  databases:
    postgres: postgres
  enableConnectionPooler: true
  enableLogicalBackup: true
  numberOfInstances: 2
  postgresql:
    version: "12"
  teamId: acid
  users:
    postgres:
      - superuser
      - createdb
  volume:
    size: 5Gi
---

