apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-meta-server
  labels:
    app: cic-meta-server
spec:
  selector:
    matchLabels:
      app: cic-meta-server
  replicas: 1
  template:
    metadata:
      labels:
        app: cic-meta-server
        group: cic-stack
    spec:
      containers:
        - name: cic-meta-server
          image: registry.gitlab.com/grassrootseconomics/cic-internal-integration/cic-meta:0.5.92
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
            - name: PGP_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: pgp-keys
                  key: password
          envFrom:
            - configMapRef:
                name: postgres-common
            - configMapRef:
                name: cic-meta
          ports:
            - containerPort: 8000
              name: cic-meta-server
          volumeMounts:
            - mountPath: /keys
              readOnly: true
              name: pgp
      volumes:
        - name: pgp
          secret:
            secretName: pgp-keys
      restartPolicy: Always
