apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana.grassecon.org
  namespace: grassroots
  labels:
    "use-http01-solver": "true"
spec:
  commonName: grafana.grassecon.org
  secretName: grafana.grassecon.org.cert
  dnsNames:
    - grafana.grassecon.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: grassroots
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.grassecon.org`)
      services:
        - name: grafana
          port: 80
  tls:
    secretName: grafana.grassecon.org.cert
