apiVersion: v1
kind: Service
metadata:
  namespace: grassroots
  name: pg-exporter
  labels:
    app: pg-exporter
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: exporter
      port: 9187
      targetPort: 9187
  selector:
    application: spilo
    team: acid
