apiVersion: v1
kind: ConfigMap
metadata:
  name: zalando-override
  namespace: grassroots
data:
  ALLOW_NOSSL: "true"
  WALG_COMPRESSION_METHOD: "brotli"
  USE_WALG_RESTORE: "true"
  USE_WALG_BACKUP: "true"
  BACKUP_SCHEDULE: "*/15 * * * *"
  BACKUP_NUM_TO_RETAIN: "100"
  AWS_REGION: ""
