apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: acid-cic-prod
  namespace: grassroots
spec:
  allowedSourceRanges: null
  databases:
    postgres: postgres
  enableConnectionPooler: false
  numberOfInstances: 2
  postgresql:
    version: "12"
  teamId: acid
  users:
    postgres:
      - superuser
      - createdb
  volume:
    size: 5Gi
