additionalArguments:
  - --entryPoints.web.http.redirections.entryPoint.to=websecure
  - --entryPoints.web.http.redirections.entryPoint.scheme=https
  - --entrypoints.web.http.redirections.entryPoint.to=:443
  - --entrypoints.web.http.redirections.entrypoint.permanent=true
  - --entrypoints.web.http.redirections.entrypoint.priority=10
  - --providers.kubernetesIngress.ingressClass=traefik-cert-manager
  - --ping=true
  - --entryPoints.web.proxyProtocol.trustedIPs=127.0.0.1/32,10.122.0.0/16
  - --entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.122.0.0/16
  - --entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.122.0.0/16
  - --entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.122.0.0/16
ingressRoute:
  dashboard:
    enabled: false
  service:
    spec:
      externalTrafficPolicy: Cluster
service:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "traefik-prod-lb"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "kube.prod.grassecon.org"
