apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: grassroots
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-credentials
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: password
