apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: grassroots
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-credentials
  data:
    - secretKey: postgres-password
      remoteRef:
        key: postgres
        property: password
